### ISSUE TITLE
Saving issue

### ISSUE THREAD

**Issue by adokova** [benvanik/xenia#484] opened 2015-12-10 19:37 UTC
So i booted up the full game and after the save screen, buttons dont respond :/ ? the demo works fine.
![su test](https://cloud.githubusercontent.com/assets/16245681/11726191/cec50472-9f7d-11e5-9722-fa7e3de09bd3.png)

**Comment by Razzile** [comment] 2015-12-10 20:51
this is probably not what the issues section is for. please post a full issue here https://github.com/xenia-project/game-compatibility

**Comment by adokova** [comment] 2015-12-10 20:51
Ok

**Comment by robert-7** [comment] 2016-12-06 19:58
@adokova can you please close this since it's not in the right place?

**Comment by maxton** [comment] 2016-12-06 20:01
This might actually be an issue with the xenia UI (if it's the buttons on that popup that aren't responding), but the issue isn't specific enough to know that

**Closed** 2017-01-03 02:32 UTC
