### ISSUE TITLE
could you try porting to windows 7?

### ISSUE THREAD

**Issue by minuteworld** [benvanik/xenia#790] opened 2017-09-21 05:50 UTC
jus' wondering.

**Comment by shadowbrony33** [comment] 2017-09-21 06:05
No, and don't open an issue for a question, use reddit.com/r/Xenia. @DrChat close this.

**Comment by Margen67** [comment] 2017-09-22 18:22
Duplicate of https://github.com/benvanik/xenia/issues/677 & https://github.com/benvanik/xenia/issues/68

**Comment by DrChat** [comment] 2017-09-25 04:06
Nope!
If you or anyone else wants to, it's potentially a simple fix that just hangs on the usage of one particular Windows API.

**Closed by DrChat** 2017-09-25 04:06 UTC
