### ISSUE TITLE
Switching active title .xex from default.xex

### ISSUE THREAD

**Issue by XeClutch** [benvanik/xenia#621] opened 2016-09-20 22:46 UTC
Say you're in the menus of COD4 and you go down to switch to multiplayer. Normally on console this would launch default_mp.xex. When doing this on xenia it just locks up. The only way to get into multiplayer is to launch specifically from default_mp.xex. You cannot do it from inside the default.xex.

**Comment by Nukem9** [comment] 2016-09-20 23:10
https://github.com/benvanik/xenia/issues/591 (fyi)

**Comment by DrChat** [comment] 2016-09-21 03:21
Yeah - duplicate of #591

**Closed by DrChat** 2016-09-21 03:21 UTC
